### ISSUE TITLE
Version 1.0.0 requires config from specific AWS SDK version

### ISSUE THREAD

**Issue by vbuchhold** [ramn/metrics_cloudwatch#38]
Since version 1.0.0, `metrics_cloudwatch::builder` takes a value of type `SdkConfig`, which comes directly from the AWS SDK. `SdkConfig` must come from the SDK version that is specified in your manifest. However, one of the packages I'm working on specifies a different SDK version in its manifest, which prevents me from calling this method. How is this supposed to work?

**Comment by ramn** [comment]
@vbuchhold can we get your feedback on #39 ?

**Comment by vbuchhold** [comment]
@ramn I don't think this solves the issue. Now I could refer to the correct type in my code, but I still cannot construct a reasonable value of this type. For this I would need a lot of other types such as the `SharedCredentialsProvider` from your SDK version. In general, I don't think it's a good idea to use types from your SDK version in your public API. This is okay for SDK crates since their releases are synchronized. But as a third-party crate, I think you need to build your own configuration abstraction.

**Comment by VladimirBramstedt** [comment]
you're right, that was my bad.
the SdkConfig type itself does not provide a way to construct one with reasonable default values. 
`SdkConfig::builder().build()` just returns an empty uninteresting config.

Before we switched to aws_sdk, the only parameter configurable was the `Region`. i think we should revert to that being the case. will make new PR.

**Comment by ramn** [comment]
@vbuchhold what do you think about this PR? https://github.com/ramn/metrics_cloudwatch/pull/40

**Comment by vbuchhold** [comment]
Would be great if setting the region wouldn't be required. I usually just let the SDK pick up the AWS region from the environment, just like the AWS credentials.

**Comment by VladimirBramstedt** [comment]
the previous version of this crate (using rusoto) had it set up this way, i was just restoring that API. 
we could make this optional i guess. fixed now in #40.

**Comment by vbuchhold** [comment]
I think this should work 👍

**Comment by ramn** [comment]
Merged so I'll close this!
