### ISSUE TITLE
Support custom Clientbuilders?

### ISSUE THREAD

**Issue by mpetri** [ramn/metrics_cloudwatch#6]
How would I go about creating a custom client builder that uses `rusoto_credential::InstanceMetadataProvider` as a credentials provider? Seems like I can't just implement a custom function similar to `default_client_builder` as the `ClientBuilder` struct is private?

**Comment by ramn** [comment]
Would your problem be solved by using this method?
https://docs.rs/metrics_cloudwatch/0.3.0/metrics_cloudwatch/struct.Builder.html#method.client_builder

It allows you to supply your own CloudWatchClient.

**Comment by mpetri** [comment]
You are right. Thanks! Very useful crate. I love it!
